export enum PassengersTypes {

    SEARCH_PASSENGERS = "SEARCH_PASSENGERS",
    SET_PASSENGER_LIST = "SET_PASSENGER_LIST",

    REQUEST_PASSENGER_INFO = "REQUEST_PASSENGER_INFO",
    SET_PASSENGER_INFO = "SET_PASSENGER_INFO",

    REQUEST_ADD_PASSENGER =  "REQUEST_ADD_PASSENGER",
    DONE_ADD_PASSENGER = "DONE_ADD_PASSENGER",

    REQUEST_EDIT_PASSENGER =  "REQUEST_EDIT_PASSENGER",
    DONE_EDIT_PASSENGER = "DONE_EDIT_PASSENGER",

    REQUEST_DELETE_PASSENGER =  "REQUEST_DELETE_PASSENGER",
    DONE_DELETE_PASSENGER = "DONE_DELETE_PASSENGER",
};